" Raghav Subramaniam
" .vimrc

" settings

set hlsearch
set incsearch
set ignorecase
set smartcase
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set autoread
set backspace=2
set hidden
set laststatus=2
set number
set wildmenu
set nobackup
set noerrorbells
set noswapfile
set notitle

set statusline=%m\ %f%=buf:%-3ncol:%-3c%y

set tags=tags;

" vim-plug

call plug#begin('~/.vim/plugged')

Plug 'romainl/apprentice'

Plug 'romainl/vim-cool'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'

Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

Plug 'junegunn/goyo.vim'

Plug 'justinj/vim-pico8-syntax'

call plug#end()

" other

colorscheme apprentice

inoremap jj <ESC>

nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k

function! s:goyo_enter()
    silent !tmux set status off
    set noautoindent
    set noshowmode
    set noshowcmd
endfunction

function! s:goyo_leave()
    silent !tmux set status on
    set autoindent
    set showmode
    set showcmd
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()

if executable('ag')
    command! -nargs=+ Ag cexpr system('ag --vimgrep ' . <q-args>)
endif
