" Raghav Subramaniam
" .vimrc

" settings

set hlsearch
set incsearch
set ignorecase
set smartcase
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set autoread
set backspace=2
set hidden
set laststatus=2
set number
set wildmenu
set nobackup
set noerrorbells
set noswapfile
set notitle

set statusline=%m\ %f%=buf:%-3ncol:%-3c%y

set tags=tags;

" vim-plug

call plug#begin('~/.vim/plugged')

Plug 'mhinz/vim-signify'

Plug 'romainl/vim-cool'

Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'

Plug 'w0ng/vim-hybrid'

call plug#end()

" other

let g:hybrid_custom_term_colors = 1
set background=dark
colorscheme hybrid

inoremap jj <ESC>

nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k

if executable('ag')
    command! -nargs=+ Ag cexpr system('ag --vimgrep ' . <q-args>)
endif
