" Raghav Subramaniam
" .vimrc

" vim-plug
call plug#begin('~/.vim/plugged')

Plug '~/.fzf'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'w0ng/vim-hybrid'

call plug#end()

" general
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set autoread
set backspace=2
set hidden
set laststatus=2
set number
set wildmenu
set nobackup
set noerrorbells
set noswapfile
set notitle

" colors
let g:hybrid_custom_term_colors=1
set background=dark
colorscheme hybrid

" avoid escape
inoremap jj <ESC>

" jk macros
nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k

" leader
let mapleader=" "

" fast buffer toggle
nnoremap <space><space> :e#<CR>

" clear searches
nnoremap <space>/ :nohlsearch<CR>

" FZF
nnoremap <space>t :FZF<CR>

" ctags
set tags=tags;

" ag
set grepprg=ag\ --vimgrep
command -nargs=* Ag grep <args>

" custom status line
set statusline=%m\ %f%=buf:%-3ncol:%-3c%y
